name: Update Translation

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  i18n-translate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run i18n:translate
      - name: Run i18n:translate
        run: npm run echo

      - name: create file
        run: echo test >> test.json

      # Step 5: Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b i18n-translation-update
          git add .
          git commit -m "SOCO: update translations via i18n:translate" || echo "No changes to commit"

      # Step 7: Create a pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          token: ${{ secrets.TOKEN }}
          branch: i18n-translation-update
          title: "Update translations"
          body: "This PR updates translations by running the i18n:translate script."
          # labels: i18n, automation
